### ISSUE TITLE
please update GoogleAds-IMA-iOS-SDK-For-AdMob

### ISSUE THREAD

**Issue by kidneyband** [googleads/googleads-ima-ios#11]
I'm using the 'GoogleAds-IMA-iOS-SDK-For-AdMob' library, but for iOS 10, we need latest 'Google-Mobile-Ads-SDK'. In this case the latest 'GoogleAds-IMA-iOS-SDK-For-AdMob' library doesn't refer to the latest  'Google-Mobile-Ads-SDK'. so can you guys update it?

**Comment by shawnbuso** [comment]
Thanks for the info - we'll get this updated with the next SDK release (we can't change the pod spec without doing another release). In the mean time, you can get an updated version of the Google Mobile Ads SDK by listing it separately in your podfile, along with GoogleAds-IMA-iOS-SDK-For-AdMob. The version you specify separately will preempt the version that IMA tries to download.
