### ISSUE TITLE
Error loading ads: Unable to request ads from server due to network error

### ISSUE THREAD

**Issue by pdpraful** [googleads/googleads-ima-ios#12]
While executing a basic sample, I am getting above error.

![screen shot 2016-09-30 at 3 15 31 pm](https://cloud.githubusercontent.com/assets/10755692/18987892/965fa75e-8721-11e6-92b8-6c647a3a9b0b.png)

**The ad tag that i am using is**: _https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=_

I am using SDK for iOS : 3.3.1

If I execute the same tag on "https://developers.google.com/interactive-media-ads/docs/sdks/flash/vastinspector" 
it works fine.

And lastly, I am running it on Simulator for iPad Air.

**Comment by shawnbuso** [comment]
Hey there,

Since this is an issue specific to your tag, could you post on the [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk)?

Thanks!
Shawn

**Comment by pdpraful** [comment]
Hi Shawn, 

This issue has been solved now. There was issue with my network firewall. The firewall was blocking all requests from doubleclick.net.

Thanks for quick response.

Thanks
Praful
