### ISSUE TITLE
Cocoapods dependency issue

### ISSUE THREAD

**Issue by ElizaSapir** [googleads/googleads-ima-ios#16]
Hey Google Team,

I am Eliza, iOS Core developer at Kaltura.

We'd like to wrap your IMA SDK in our podspec.

When I add the dependency `ssp.dependency 'GoogleAds-IMA-iOS-SDK'` into the podspec, I get the following error:

```

    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds-GoogleIMA3/GoogleInteractiveMediaAds.framework)) during validation.

```

Do you have any solution for me? maybe you already have some beta dynamic version I can use?

You can see similar issue that was resolved on `Youbora-AVPlayer-iOS` sdk (https://github.com/NicePeopleAtWork/Youbora-AVPlayer-iOS/issues/1).

**Comment by shawnbuso** [comment]
We're aware of this issue and still working on a solution - the issue is that the IMA SDK is not yet a dynamic library, so once we have that conversion complete (which we're working on right now) this issue should go away.

**Comment by shawnbuso** [comment]
Hi Eliza,

Our recommended support path for issues not specific to these samples is to go through our [support forum](https://groups.google.com/forum/?fromgroups#!forum/ima-sdk). We're aware of this issue and are working on a dynamic version of the library, but we don't have anything (beta or non-beta) to release at this time.

Thanks,
Shawn

**Comment by ElizaSapir** [comment]
Hey @shawnbuso  your new release resolves my issue.

Thanks!
