### ISSUE TITLE
Third Party ad server support

### ISSUE THREAD

**Issue by saravananmaruthanayakam** [googleads/googleads-ima-ios#17]
I am requesting a Third party ad .

i Get the following error: Unable to request the ads from the server due to the network error.

My VAST ad tag -"http://az739004.vo.msecnd.net/vast/vast_twitter.xml"

**Comment by shawnbuso** [comment]
Hey there,

For general support (i.e. any issue not specific to these samples) please check out our support forum.

Thanks!
Shawn Busolits
IMA SDK Team
