### ISSUE TITLE
Issue with timer on arabic version.

### ISSUE THREAD

**Issue by bernikowich-cedoni** [googleads/googleads-ima-ios#2]
We have issue with timer on arabic version while showing preroll. You can contact me for more details by Skype (bernikowich) or here.

**Comment by shawnbuso** [comment]
Could you give us some more details? What specific issue are you seeing, how to do you replicate it, what browsers are you using?

**Comment by bernikowich-cedoni** [comment]
Here is the image. We use not the latest version (not 2.1.0), but we'll update it tomorrow. I will notify you if something changes.
<img width="751" alt="screen shot 2015-12-23 at 1 27 33 pm" src="https://cloud.githubusercontent.com/assets/11190974/11974831/f65c9d42-a978-11e5-911c-3917909ae472.png">

**Comment by Anastasiya-Netco** [comment]
@shawnbuso Hello,
Do you have any news on the provided issue? It still exists though we updated SDK to 3.1.0. Do you have any ideas when it can be fixed?

Thank you!

**Comment by shawnbuso** [comment]
Could you send me the ad tag you're using so I can test on my end? Thanks!

**Comment by Anastasiya-Netco** [comment]
Please, try this one https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/176111452/app_mena_arabic&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]
