### ISSUE TITLE
AdStart Buffering settings

### ISSUE THREAD

**Issue by gal-orlanczyk** [googleads/googleads-ima-ios#20]
Hi, 

Do you plan to add the ability to change default timeout time for ad video buffering on iOS?
Currently from what I understood it is 15 seconds, which is long and could be very helpful if it will be adjustable per usage.

Thanks
Gal

**Comment by shawnbuso** [comment]
Hi Gal,

The issue tracker here is used for issues specific to these samples - for general SDK questions you'll find help on our [support forum](https://groups.google.com/group/ima-sdk).

Thanks!
Shawn
