### ISSUE TITLE
Check already played ads

### ISSUE THREAD

**Issue by thomasjoulin** [googleads/googleads-ima-ios#21]
Is there a way to check which ads were played already? I see `IMACuepoint isPlayed` but used only in `IMAStreamManager previousCuepointForStreamTime`. Does it mean I have to call this in a loop?

**Comment by shawnbuso** [comment]
Hey Thomas,

Since this isn't an issue specific to these samples, could you reach out to our [support forum](groups.google.com/group/ima-sdk)? You'll get better support and a faster response there.

Thanks,
Shawn

**Comment by thomasjoulin** [comment]
Thanks! Can close :)
