### ISSUE TITLE
No ad provided in adsManager:didReceiveEvent when event is kIMAAdEvent_LOG

### ISSUE THREAD

**Issue by thomasjoulin** [googleads/googleads-ima-ios#22]
I get `kIMAError_VAST_EMPTY_RESPONSE` error as the ad couldn't be fetched, but `event.ad` is `nil` so I don't know which ad failed to play

**Comment by shawnbuso** [comment]
Do you have a tag I can test with? If you're getting VAST_EMPTY_RESPONSE it means the ad server responded but didn't have an ad for you, so that's why you're getting nil for the ad. So you're not getting an ad from the event because the SDK never got an ad from the server.

**Comment by thomasjoulin** [comment]
Sure, can I send it to you privately? I get a list of ads from pubads.g.doubleclick.net/gampad/ads but each ad URL returns:

```
<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0"/>
```

This is not a problem, but I just want to catch the event so I can remove the ad, as if it was played. I show yellow markers like Youtube and remove them once played (or in this case failed to be played)

**Comment by shawnbuso** [comment]
Sure thing - if you want to send it privately, you can email ima-sdk-support@google.com and someone from our team will pick it up :)

**Comment by thomasjoulin** [comment]
Thanks! Can close :)
