### ISSUE TITLE
Issue with ad container not in view hierarchy

### ISSUE THREAD

**Issue by gal-orlanczyk** [googleads/googleads-ima-ios#23]
Hi,

Since updating to version 3.5.2 I have been seeing the error: "Ads cannot be requested because the ad container is not attached to the view hierarchy".
For sure my view  is in the view hierarchy but what I noticed is this:
when I call remove from superview before the video view controller is disappearing and destroying IMA instance the IMA SDK probably doesn't reset it's states and in the next time I request ads it fails with this error, on the first time everything works fine and it usually happens if I quit in the middle of an ad.

Thanks,
Gal

**Comment by shawnbuso** [comment]
Hey Gal,

For issues like this you'll get a faster response via the [support forum](https://groups.google.com/group/ima-sdk) - would you mind posting there?

Thanks!
Shawn Busolits
IMA SDK Team
