### ISSUE TITLE
Non Linear Ads

### ISSUE THREAD

**Issue by kumar153** [googleads/googleads-ima-ios#24]
Non Linear Ads are not working in this player , can any one check this issue i am mentioning the links:

VAST 1.0 Non Linear
http://demo.tremorvideo.com/proddev/vast/vast1Nonlinear.xml

VAST 2.0 Non Linear
http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml

**Comment by shawnbuso** [comment]
Hi there - we currently don't support non-linear ads in our iOS or Android SDKs. You can see a list of supported features [here](https://developers.google.com/interactive-media-ads/docs/sdks/ios/compatibility). Thanks!
