### ISSUE TITLE
I am not play to resume ad when app comes in a foreground

### ISSUE THREAD

**Issue by vivekathilkar** [googleads/googleads-ima-ios#28]
Helo there
I using "GoogleAds-IMA-iOS-SDK', '~> 3.7" that working fine, but when app comes in  foreground mode from background mode ad is not resumes, that gets stucks. I am able to achieve this using notifications on app level. 

In SDK is there any property do I need to set so can automatically handle that, without app level coding i.e notification.

Thanks,
Vivek

**Comment by shawnbuso** [comment]
Hi there - this sounds like it's not specific to these samples. Would you mind posting on our [support forum](https://groups.google.com/group/ima-sdk)? Thanks!
