### ISSUE TITLE
Add a bridging header in Swift sample project

### ISSUE THREAD

**Issue by ruudkalis** [googleads/googleads-ima-ios#3]
Hi! I just installed the googleads_ima_ios_swift_basic_example project and used pods to install the GoogleInteractiveMediaAds framework. Building the project gives the following errors in `GoogleInteractiveMediaAds.h`:

`"Include of non-modular header inside framework module 'GoogleInteractiveMediaAds'"`

Please add a bridging header with the following code to the Swift projects and add this header in the Build Settings under **Objective-C Bridging Header**.

`#import <GoogleInteractiveMediaAds/GoogleInteractiveMediaAds.h>`

**Comment by shawnbuso** [comment]
Hi there,

Which version of XCode are you using? I'm not seeing this in the sample on my end - I'm able to build and run with Cocoapods without issue, and without adding the bridging header.

Thanks,
Shawn

**Comment by ruudkalis** [comment]
Hi Shawn, thanks for your reply! I am using XCode 7.2.1 (build 7C1002), which I believe is the latest non-beta release. Just ran the same procedure. Downloaded the project, opened terminal and did pod install. Then opened BasicExample.xcworkspace, select my iPhone 6 as destination and build. Get this:

<img width="1280" alt="screen shot 2016-02-23 at 19 48 10" src="https://cloud.githubusercontent.com/assets/14074723/13262747/ba2ba5d8-da66-11e5-8f10-0801cb89fa41.png">

Did you test with a clean install of the project?

**Comment by shawnbuso** [comment]
Ah OK I am now seeing this on my end as well (I had to update XCode). I'm going to work with the team to see if we can somehow fix this from within the SDK itself, but if not we will add bridge headers to get this working.

**Comment by ruudkalis** [comment]
Hi Shawn, 

Thanks for you effort! 

I have never built a framework myself but from what I believe you cannot avoid a bridging header when using a framework with objective-c code into a project with Swift code. The umbrella header that causes the error needs to be imported via a bridging header. 

The only way to avoid a bridging header is to re-write the framework in Swift.

Find more information about [Mix and Match](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) on Apple's website.

Cheers, 
Ruud

**Comment by shawnbuso** [comment]
Hi there,

We were actually able to get around this by modifying our module map to include a list of the header files. This will be included in our next release. In the mean time, after running pod install you can navigate to Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds-GoogleIMA3/GoogleInteractiveMediaAds.framework/Modules/module.modulemap and add the following to that file right before the closing "}" (you'll need to change the permissions on that file to make it read-write instead of read only):

    header "IMAAVPlayerContentPlayhead.h"
    header "IMAAVPlayerVideoDisplay.h"
    header "IMAAd.h"
    header "IMAAdDisplayContainer.h"
    header "IMAAdError.h"
    header "IMAAdEvent.h"
    header "IMAAdPlaybackInfo.h"
    header "IMAAdPodInfo.h"
    header "IMAAdsLoader.h"
    header "IMAAdsManager.h"
    header "IMAAdsRenderingSettings.h"
    header "IMAAdsRequest.h"
    header "IMACompanionAdSlot.h"
    header "IMAContentPlayhead.h"
    header "IMAPictureInPictureProxy.h"
    header "IMASettings.h"
    header "IMAStreamManager.h"
    header "IMAStreamRequest.h"
    header "IMAUiElements.h"
    header "IMAVideoDisplay.h"

If you need any more help let me know!

Thanks,
Shawn

**Comment by shawnbuso** [comment]
This should be fixed with the most recent iOS release, 3.2.0. If you're still seeing the issue there let us know!

**Comment by ruudkalis** [comment]
Thanks for the update Shawn!
