### ISSUE TITLE
issue : Include of non-modular header inside framework module 

### ISSUE THREAD

**Issue by PoissonBallon** [googleads/googleads-ima-ios#5]
No news about this issue : #https://github.com/googleads/googleads-ima-ios/issues/3  ? i have the same issue :s 

IDE : Xcode 7.3
Cocoapods 0.39

**Comment by shawnbuso** [comment]
This should be fixed with the most recent iOS release, 3.2.0. If you're still seeing the issue there let us know!

**Comment by GerritPost** [comment]
It's working again! Thanks

**Comment by PoissonBallon** [comment]
With : pod 'GoogleAds-IMA-iOS-SDK', '~> 3.2.0'

`duplicate symbol _OBJC_CLASS_$_GAD_GTMStringEncoding in:

/Users/.../Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds-GoogleIMA3/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds(GAD_GTMStringEncoding.o)
/Users/.../Pods/Google-Mobile-Ads-SDK/GoogleMobileAdsSdkiOS-7.7.1/GoogleMobileAds.framework/GoogleMobileAds(flat-x86_64)
duplicate symbol _OBJC_METACLASS_$_GAD_GTMStringEncoding in:

ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

With :   pod 'GoogleAds-IMA-iOS-SDK-For-AdMob', '~> 3.2.0'

All it's ok !! Thx you for your work guys :) 💯 🚀
