### ISSUE TITLE
Warning when "dwarf-with-dsym"

### ISSUE THREAD

**Issue by bernikowich-cedoni** [googleads/googleads-ima-ios#6]
Hello.
I've tried to create new empty project and add your library with CocoaPods. Then after disabling bit code and enabling "dwarf-with-dsym" I've a lot of warnings.

**Comment by shawnbuso** [comment]
Hi,

Could you please post the specific warnings you're getting in our [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk)?

Thanks!
