### ISSUE TITLE
App Transport Security compliance

### ISSUE THREAD

**Issue by Matthew-C** [googleads/googleads-ima-ios#9]
Hi,

Apple is going to enforce ATS on 1/1/2017, is there any plan to make IMA comply with ATS?

**Comment by shawnbuso** [comment]
The SDK itself is currently HTTPS compliant - the samples are currently disabling ATS only because we haven't yet migrated our sample content videos to an HTTPS source. So as long as you have HTTPS content video and ad sources you should be fine.
